import Head from "next/head"
import Stats from "../components/Stats"

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>NextJS and Tailwind Template</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex items-center justify-center h-screen bg-mainBackGround">
        <Stats companies="10k+" templates="314" queries="12M+" />
      </main>
    </div>
  )
}
